(defun color-theme-bossy ()
  "Brown color theme.  Very different from the others.
Supports standard, font-lock and info faces, and it uses
`color-theme-blue-gnus', `color-theme-blue-erc' , and
`color-theme-beige-diff'."
  (interactive)
  (color-theme-blue-gnus)
  (let ((color-theme-is-cumulative t))
    (color-theme-blue-erc)
    (color-theme-beige-diff)
    (color-theme-beige-eshell)
    (color-theme-install
     '(color-theme-bossy
       ((background-color . "#281114")
	(Background-mode . dark)
	(border-color . "black")
	(cursor-color . "light goldenrod")
	(foreground-color . "goldenrod")
	(mouse-color . "goldenrod"))
       ((goto-address-mail-face . info-xref)
	(list-matching-lines-face . bold)
	(view-highlight-face . highlight))
       (default ((t (nil))))
       (bold ((t (:bold t))))
       (bold-italic ((t (:italic t :bold t :foreground "lavender"))))
       (font-lock-builtin-face ((t (:foreground "pale goldenrod"))))
       (font-lock-comment-face ((t (:foreground "indian red"))))
       (font-lock-constant-face ((t (:foreground "pale green"))))
       (font-lock-function-name-face ((t (:bold t :foreground "lemon chiffon"))))
       (font-lock-keyword-face ((t (:foreground "wheat"))))
       (font-lock-string-face ((t (:foreground "gold"))))
       (font-lock-type-face ((t (:foreground "dark khaki" :bold t))))
       (font-lock-variable-name-face ((t (:bold t :foreground "khaki"))))
       (font-lock-warning-face ((t (:bold t :foreground "orange red"))))
       (fringe ((t (:background "#111111"))))
       (header-line ((t (:background "gray20" :foreground "gray70"))))
       (highlight ((t (:background "dark slate blue"))))
       (info-menu-5 ((t (:underline t))))
       (info-node ((t (:bold t))))
       (info-xref ((t (:bold t :foreground "pale goldenrod"))))
       (isearch ((t (:background "SeaGreen4"))))
       (isearch-lazy-highlight-face ((t (:background "DarkOliveGreen4"))))
       (italic ((t (:italic t :foreground "lavender"))))
       (menu ((t (:background "gray25" :foreground "lemon chiffon"))))
       (modeline ((t (:background "gray40" :foreground "lemon chiffon" :box (:line-width 1 :style released-button)))))
       (modeline-buffer-id ((t (:background "AntiqueWhite4" :foreground "lemon chiffon"))))
       (modeline-mousable ((t (:background "AntiqueWhite4" :foreground "lemon chiffon"))))
       (modeline-mousable-minor-mode ((t (:background "wheat" :foreground "lemon chiffon"))))
       (mode-line-inactive ((t (:background "gray20" :foreground "lemon chiffon" :box (:line-width 1 :style released-button)))))
       (region ((t (:background "dark olive green"))))
       (secondary-selection ((t (:background "dark green"))))
       (tool-bar ((t (:background "gray25" :foreground "lemon chiffon" :box (:line-width 1 :style released-button)))))
       (underline ((t (:underline t))))))))
